// NOTE: THIS MODULE IS AUTOGENERATED
//       DO NOT EDIT BY HAND!
module pipreg_id_ex(

  input [31:0] id_pc,
  input [31:0] id_A,
  input [31:0] id_B,
  input [4:0] id_A_reg,
  input [4:0] id_B_reg,
  input [0:0] id_B_imm,
  input [4:0] id_shamt,
  input [11:0] id_opc,
  input [0:0] id_alu_inst,
  input [0:0] id_load_inst,
  input [0:0] id_store_inst,
  input [0:0] id_jmp_inst,
  input [4:0] id_dest_reg,
  input [0:0] id_dest_reg_valid,


  output reg [31:0] ex_pc,
  output reg [31:0] ex_A,
  output reg [31:0] ex_B,
  output reg [4:0] ex_A_reg,
  output reg [4:0] ex_B_reg,
  output reg [0:0] ex_B_imm,
  output reg [4:0] ex_shamt,
  output reg [11:0] ex_opc,
  output reg [0:0] ex_alu_inst,
  output reg [0:0] ex_load_inst,
  output reg [0:0] ex_store_inst,
  output reg [0:0] ex_jmp_inst,
  output reg [4:0] ex_dest_reg,
  output reg [0:0] ex_dest_reg_valid,

  input clock,
  input reset_n
);

  always_ff @(posedge clock, negedge reset_n) begin
    if (~reset_n) begin
    
      ex_pc <= 'b0;
      ex_A <= 'b0;
      ex_B <= 'b0;
      ex_A_reg <= 'b0;
      ex_B_reg <= 'b0;
      ex_B_imm <= 'b0;
      ex_shamt <= 'b0;
      ex_opc <= 'b0;
      ex_alu_inst <= 'b0;
      ex_load_inst <= 'b0;
      ex_store_inst <= 'b0;
      ex_jmp_inst <= 'b0;
      ex_dest_reg <= 'b0;
      ex_dest_reg_valid <= 'b0;
    end
    else begin
    
      ex_pc <= id_pc;
      ex_A <= id_A;
      ex_B <= id_B;
      ex_A_reg <= id_A_reg;
      ex_B_reg <= id_B_reg;
      ex_B_imm <= id_B_imm;
      ex_shamt <= id_shamt;
      ex_opc <= id_opc;
      ex_alu_inst <= id_alu_inst;
      ex_load_inst <= id_load_inst;
      ex_store_inst <= id_store_inst;
      ex_jmp_inst <= id_jmp_inst;
      ex_dest_reg <= id_dest_reg;
      ex_dest_reg_valid <= id_dest_reg_valid;
    end
  end

endmodule
